baseURL = "https://kracekumar.com/"
languageCode = "en-us"
title = "Technical Ramblings"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
        useHLJS = true
        mainSections = ["post","posts"]
        rss = true
        wordCount = true
        showRelatedPosts = true

[[menu.main]]
        name = "Blog"
        url = ""
        weight = 1

[[menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[markup.goldmark.renderer]
        unsafe= true


